[package]
name = "fractal_explorer"
version = "0.1.0"
authors = ["Gines Espada Almansa <gines.espada@gmail.com>"]

[dependencies]
num = "0.1.27"
sdl2 = "*"
eventual= "*"

[dependencies.fractal_generation]
path = "fractal_generation"